### ISSUE TITLE
struktura addUser

### ISSUE THREAD

**Issue by pohadkar** [igloonet/mailkit-api#12]
v dokumentaci mailkitu viz. https://www.mailkit.cz/podpora/api/sprava-seznamu-prijemcu/mailkitmailinglistadduser je uvedeno, že v tomto XML existuje větev PARAMS, která by se měla volitelně posílat při volbě double opt-in = false. obsahuje parametry ip_src a form_url.

je možné tuto větev ve vašem api nějak naplnit, nebo jste ji nezpracovávali?
v definici funkce addUser v UsersManager.php tu možnost bohužel nevidím.

**Comment by fejjo** [comment]
Ahoj, bohužial sme to zatiaľ nepotrebovali tak je možné iba nastaviť boolean na double opt-in.
