### ISSUE TITLE
nefunkčnost na php 7.3

### ISSUE THREAD

**Issue by pohadkar** [igloonet/mailkit-api#14]
dobrý den,
dnes jsme zvedli verzi php z 7.2 na 7.3 a mailkit-api prestalo fungovat.

hlasi to chybu:
Fatal error: Uncaught Error: Call to undefined function Igloonet\MailkitApi\RPC\Adapters\xmlrpc_encode_request()

zrejme byla ta funkce v php 7.3 zrusena nebo prejmenovana.
dokazete poradit jak to opravit, nebo se musime vratit k php 7.2?

**Comment by pohadkar** [comment]
aaa, tak vyreseno doinstalovanim modulu xmlrpc do php 7.3. uz to zase jede. kdyby nekdo mel stejny problem :)

**Comment by sobolcz** [comment]
Dobrý den,

samotné xmlrpc máte povolené a aktualizovatné v sytému? V phpinfu jej vidíte povolené? Restart všech služeb jste po upgradu, předpokládám provedli?

**Comment by pohadkar** [comment]
nebylo tam. moje chyba, ze jsem to nezkontroloval. nevedel jsem, ze se to musi zvlast. takze uz vyreseno.
