### ISSUE TITLE
chyba pri posilani zanorene struktury $templateVars

### ISSUE THREAD

**Issue by pohadkar** [igloonet/mailkit-api#9]
chyba je v souboru mailkit-api/src/Managers/MessagesManager.php na radku 40.
konkretne zde provadite array_map ale predpokladate pritom, ze pole template vars ma jen jednoduchou strukturu
```
		$templateVars = array_map(
			function (string $value) {
				return $this->encodeString($value);
			},
			$message->getTemplateVars()
		);
```
pokud pole obsahuje vnitrni strukturu, napriklad zbozi s prvky [0][1][2] atd a v nich jsou jeste dalsi asociativni prvky, tak tady ten kod vyhodi chybu a dal nepokracuje.

je mozne ze toto je jen zacatek problemu. zkusil jsem to obejit, a pouzil encodeString i na vnorene prvky pole, ale zda se ze, na mailkit api odesla jen prvni uroven hodnot a zanorene pak stejne neodesly.

**Comment by fejjo** [comment]
Ahoj mergol som tam fix aby preslo aj viac rozmerne pole. Malo by to byt v pohode ak by bol nejaky problem tak hod na mna issue
